-- =========================================================
-- Raw transaction table and production load format
-- =========================================================

USE ROLE SYSADMIN;
USE WAREHOUSE RETAIL_ANALYTICS_WH;
USE DATABASE CUSTOMER_REVENUE_RETENTION_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE TRANSACTIONS_CLEAN_RAW (
    INVOICE_NO          VARCHAR(30),
    STOCK_CODE          VARCHAR(50),
    DESCRIPTION         VARCHAR(500),
    QUANTITY            NUMBER(18, 0),
    INVOICE_DATE        TIMESTAMP_NTZ,
    UNIT_PRICE          NUMBER(18, 4),
    CUSTOMER_ID         NUMBER(18, 0),
    COUNTRY             VARCHAR(100),
    SOURCE_YEAR         VARCHAR(20),
    TRANSACTION_TYPE    VARCHAR(100),
    LINE_CATEGORY       VARCHAR(100),
    LINE_VALUE          NUMBER(20, 4),
    DATA_QUALITY_FLAG   VARCHAR(500),
    ANALYSIS_ELIGIBLE   BOOLEAN
);

CREATE OR REPLACE FILE FORMAT CSV_GZIP_LOAD_FORMAT
    TYPE = CSV
    COMPRESSION = AUTO
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null', 'NaN')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    TIMESTAMP_FORMAT = AUTO
    ENCODING = 'UTF8';

DESCRIBE TABLE TRANSACTIONS_CLEAN_RAW;


