-- =========================================================
-- Final Snowflake warehouse validation
-- =========================================================

USE ROLE SYSADMIN;
USE WAREHOUSE RETAIL_ANALYTICS_WH;
USE DATABASE CUSTOMER_REVENUE_RETENTION_DB;

SELECT
    -- Transaction-layer checks
    (SELECT COUNT(*)
     FROM RAW.TRANSACTIONS_CLEAN_RAW)
        AS RAW_ROWS,

    (SELECT COUNT(*)
     FROM STAGING.VW_TRANSACTIONS_STANDARDIZED)
        AS STAGING_ROWS,

    -- Revenue checks
    (SELECT GROSS_MERCHANDISE_SALES
     FROM ANALYTICS.MART_REVENUE_KPIS)
        AS GROSS_MERCHANDISE_SALES,

    (SELECT NET_REVENUE
     FROM ANALYTICS.MART_REVENUE_KPIS)
        AS NET_REVENUE,

    -- Customer checks
    (SELECT COUNT(*)
     FROM ANALYTICS.CUSTOMER_RFM_SEGMENTS)
        AS RFM_CUSTOMERS,

    (SELECT CUSTOMER_COUNT
     FROM ANALYTICS.MART_CUSTOMER_SEGMENTS
     WHERE CUSTOMER_SEGMENT = 'Champions')
        AS CHAMPIONS_CUSTOMERS,

    -- Retention checks
    (SELECT MONTH_2_RETENTION_PCT
     FROM ANALYTICS.MART_RETENTION_KPIS)
        AS MONTH_2_RETENTION_PCT,

    (SELECT MONTH_12_RETENTION_PCT
     FROM ANALYTICS.MART_RETENTION_KPIS)
        AS MONTH_12_RETENTION_PCT,

    -- GenAI checks
    (SELECT COUNT(*)
     FROM ANALYTICS.GENAI_PRODUCT_CLASSIFICATIONS)
        AS GENAI_PRODUCT_ROWS,

    -- The finalized GenAI taxonomy contains 12 categories
(SELECT COUNT(DISTINCT PRODUCT_CATEGORY)
 FROM ANALYTICS.GENAI_PRODUCT_CLASSIFICATIONS)
    AS PRODUCT_CATEGORIES,

-- Additional transparent bucket for non-sale-only stock codes
(SELECT COUNT_IF(PRODUCT_CATEGORY = 'Unclassified')
 FROM ANALYTICS.MART_CATEGORY_PERFORMANCE)
    AS TECHNICAL_UNCLASSIFIED_BUCKETS,

    -- Object check
    (
        SELECT COUNT(*)
        FROM CUSTOMER_REVENUE_RETENTION_DB.INFORMATION_SCHEMA.VIEWS
        WHERE TABLE_SCHEMA = 'ANALYTICS'
          AND TABLE_NAME IN (
              'MART_REVENUE_KPIS',
              'MART_MONTHLY_REVENUE',
              'DIM_CUSTOMER',
              'MART_CUSTOMER_TYPE_SUMMARY',
              'DIM_CUSTOMER_COHORT',
              'MART_COHORT_RETENTION',
              'MART_RETENTION_KPIS',
              'MART_CUSTOMER_SEGMENTS',
              'VW_ENRICHED_MERCHANDISE_TRANSACTIONS',
              'MART_CATEGORY_PERFORMANCE'
          )
    ) AS REQUIRED_ANALYTICS_VIEWS;





